name: updatedb

# on:
#   schedule:
#     - cron: '0 0 * * *'  # Runs every day at midnight UTC
on:
  workflow_dispatch:
    inputs:
      input:
        description: "manual"
        required: false
        default: "true"
  schedule:
    - cron: '0 0 * * *'
jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update DB
      env:
        LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
      run: |
        cd ~/
        wget -O GeoLite2-ASN.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=$LICENSE_KEY&suffix=tar.gz"
        wget -O GeoLite2-City.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$LICENSE_KEY&suffix=tar.gz"
        curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
        sudo apt update &&  sudo apt install elasticsearch -y
        mkdir ~/elastic
        tar -xvf GeoLite2-ASN.tar.gz
        tar -xvf GeoLite2-City.tar.gz
        find ~/ -name "*.mmdb" -exec cp "{}" ~/elastic  \; 
        ls -la ~/elastic
        cd ~/elastic
        sudo /usr/share/elasticsearch/bin/elasticsearch-geoip -s ~/elastic
        rm -rf ~/elastic/*.mmdb
        tar -cvf ~/filter_geo.tar .
        sha1sum ~/filter_geo.tar > ~/filter_geo.tar.sha1
        ls -la
        pwd
        
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Test with environment variables
      run: echo $TAG_NAME - $RELEASE_NAME
      env:
        TAG_NAME: daily-release-${{ steps.date.outputs.date }}
        RELEASE_NAME: daily-release-${{ steps.date.outputs.date }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: daily-release-${{ steps.date.outputs.date }}
        release_name: daily-release-${{ steps.date.outputs.date }}
        body: Dialy ip filter release ${{ steps.date.outputs.date }}
    - name: Upload Release Asset
      id: upload-release-asset
      uses: sekwah41/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: /home/runner/filter_geo.tar
        asset_name: filter_geo.tar
        asset_content_type: application/x-tar
    - name: Upload Release Asset
      id: upload-release-asset-hash
      uses: sekwah41/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: /home/runner/filter_geo.tar.sha1
        asset_name: filter_geo.tar.sha1
        asset_content_type: text/plain
        
